Typos arreglados y texto agregado
fedevmoreno/hyperblog pull request #1
Opened 2020-10-21 17:30 UTC by fedevmoreno

No debimos pasar este error a master.

2020-10-21 22:16 UTC, Nitramcr reviewed
Nice changes dude! Remember never stop learning.

2020-10-21 23:56 UTC, fedevmoreno commented
> Nice changes dude! Remember never stop learning.

Jaja. Ahora tengo que ver qué tenés que hacer!

2020-10-28 23:16 UTC, Nitramcr requested changes
En vez de usar tildes directas, usa entidades HTML. No seas Roberto.

2020-11-02 20:25 UTC, fedevmoreno commented
Cambios hechos. Por favor, utiliza tus Rasengan y tus Rasen Shuriken para hacerme el merge.

2020-11-02 21:40 UTC, Nitramcr approved these changes
Excelente, de veras!

2020-11-02 22:03 UTC, merged